language: node_js
node_js: 
- "6"
env: 
matrix:
 - AUTH=true
 - USER=test
 - PASSWORD=secret
before_script:
 - npm start
script: 
  - npm test 
  - npm run lint
branches: 
  only: 
   - master
notifications:
   email:
    - dennis.wolters@upb.de
    